### ISSUE TITLE
It's "Drunk in Love" sorry y'all

### ISSUE THREAD

**Issue by clintonn** [learn-co-curriculum/ruby-objects-has-many-through-readme#15]
Bey did have a song in 2003 called "Crazy in Love" so I'll give you that, but the one with Jay-Z is "Drunk in Love."

🐝

**Comment by gj** [comment]
Hey @clintonn !

Jay Z is also on ["Crazy in Love"](https://www.youtube.com/watch?v=ViwtNLUqkMY) 🙂
