### ISSUE TITLE
Typo- 2 'ands' in third line of text

### ISSUE THREAD

**Issue by ccklight** [learn-co-curriculum/ruby-objects-has-many-through-readme#18]
In addition to these one-to-one and one-to-many relationships, there are relationships that need something to join them together. For example, you don't need to have a direct relationship with the pilot of a flight you're on. You have a relationship with that flight (you're taking the flight after all), and and the pilot has a relationship with the flight (they're flying it). So you have a relationship to that pilot through the flight.

**Comment by drakeltheryuujin** [comment]
Thank you for pointing this out. We've updated the materials and believe that it is fixed. 💙
