### ISSUE TITLE
Possible typo on line 34 of last code example

### ISSUE THREAD

**Issue by JoeQuattrone** [learn-co-curriculum/ruby-objects-has-many-through-readme#19]
The method is 

```ruby
 def new_meal_20_percent(waiter, total)
    tip = total * 0.2
    Meal.new(waiter, total, tip)
  end
```

I think this would error out because Meal.new takes in four arguments:  (waiter, customer, total, tip) and I don't believe customer is set to self on default, at least not explicitly stated in the earlier text. Unless I'm missing something here, this is a bit confusing.

**Comment by sgharms** [comment]
You're right! Fixed!
