### ISSUE TITLE
wrong info being passed into Waiter initialization

### ISSUE THREAD

**Issue by Lukas-Roberts** [learn-co-curriculum/ruby-objects-has-many-through-readme#21]
the Waiter class gets initialized with a name and years experience. The 6th picture of code, two waiters get initialized with an age instead of years experience. `pat = Waiter.new("Pat", 22)`
  `alex = Waiter.new("Alex", 35)` not that pat and alex wouldn't have 22 years of exp and 35 years exp. That would make alex at least 56 years old.

**Comment by maxwellbenton** [comment]
Hi @PineappleGuy,

We've updated this lesson's readme and fixed the years of experience, which should resolve this issue. Thanks for providing this feedback!
