### ISSUE TITLE
Please convert into a Code !!!

### ISSUE THREAD

**Issue by Nerajno** [learn-co-curriculum/ruby-objects-has-many-through-readme#22]
Please convert into a code along with learn specs. It allows the learner to make and retain more of this concept of "has many through"; reinforces the concepts( one to many and belongs to) and gives the learner much needed practice. 
@maxwellbenton 
=> @Nerajno if needed for more explanation.

**Comment by maxwellbenton** [comment]
Hi @Nerajno,

Thank you for opening this issue and providing this feedback. We are in the process of updating the materials in this section and have updated this lesson's readme, included support files and tests that are solvable by coding along with the readme, which should resolve this issue.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

Thank you for contributing to a Learn lesson!
